<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AzureCosmosDisableNewtonsoftJsonCheck>true</AzureCosmosDisableNewtonsoftJsonCheck>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
		<PackageReference Include="AspNetCore.HealthChecks.CosmosDb" Version="8.0.1" />
		<PackageReference Include="AspNetCore.HealthChecks.Redis" Version="8.0.1" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\SmartDesk.Application\SmartDesk.Application.csproj" />
		<ProjectReference Include="..\SmartDesk.Infrastructure\SmartDesk.Infrastructure.csproj" />
	</ItemGroup>
</Project>